// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace _060_Test_Security_GatUser_Log_GATP_2465
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v19_2;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ChangeUserCredentials - Use 'ChangeUserCredentialsParams' to pass parameters into this method.
        /// </summary>
        public void ChangeUserCredentials()
        {
            #region Variable Declarations
            WinClient uIPanel16Client = this.UIBrukeradministrasjonWindow.UIItemWindow.UIPanel16Client;
            WinClient uIItemClient = this.UIBrukeradministrasjonWindow.UIItemWindow1.UIItemClient;
            WinEdit uIItemEdit = this.UIBrukeradministrasjonWindow.UIItemWindow21.UIItemEdit;
            WinEdit uIItemEdit1 = this.UIBrukeradministrasjonWindow.UIItemWindow31.UIItemEdit;
            WinEdit uIItemEdit2 = this.UIBrukeradministrasjonWindow.UIItemWindow2.UIItemEdit;
            WinEdit uIItemEdit3 = this.UIBrukeradministrasjonWindow.UIItem0xf427ef86dcac25Window.UIItemEdit;
            WinEdit uIItemEdit4 = this.UIBrukeradministrasjonWindow.UIItemWindow5.UIItemEdit;
            WinEdit uIItemEdit5 = this.UIBrukeradministrasjonWindow.UIItemWindow6.UIItemEdit;
            WinEdit uIItemEdit6 = this.UIBrukeradministrasjonWindow.UIItemWindow7.UIItemEdit;
            WinEdit uIItemEdit7 = this.UIBrukeradministrasjonWindow.UIItemWindow81.UIItemEdit;
            WinEdit uIItemEdit8 = this.UIBrukeradministrasjonWindow.UIItemWindow82.UIItemEdit;
            WinEdit uIItemEdit9 = this.UIBrukeradministrasjonWindow.UIItemWindow91.UIItemEdit;
            WinEdit uIItemEdit10 = this.UIBrukeradministrasjonWindow.UIItemWindow92.UIItemEdit;
            WinEdit uIItemEdit11 = this.UIBrukeradministrasjonWindow.UIItemWindow101.UIItemEdit;
            WinEdit uIItemEdit12 = this.UIBrukeradministrasjonWindow.UIItemWindow102.UIItemEdit;
            WinEdit uIItemEdit13 = this.UIBrukeradministrasjonWindow.UIItemWindow13.UIItemEdit;
            WinEdit uIItemEdit14 = this.UIBrukeradministrasjonWindow.UIItemWindow9.UIItemEdit;
            WinEdit uIItemEdit15 = this.UIBrukeradministrasjonWindow.UIItemWindow10.UIItemEdit;
            WinButton uIOKButton = this.UIBrukeradministrasjonWindow.UIItemWindow3.UIItemClient.UIOKButton;
            #endregion

            // Click 'Panel16' client
            Mouse.Click(uIPanel16Client, new Point(64, 594));

            // Click client
            Mouse.Click(uIItemClient, new Point(49, 8));

            // Type 'BASTANT2' in text box
            uIItemEdit.Text = this.ChangeUserCredentialsParams.UIItemEditText;

            // Type 'BJARNE2' in text box
            uIItemEdit1.Text = this.ChangeUserCredentialsParams.UIItemEditText1;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit1, this.ChangeUserCredentialsParams.UIItemEditSendKeys, ModifierKeys.None);

            // Type '********' in text box
            Keyboard.SendKeys(uIItemEdit2, this.ChangeUserCredentialsParams.UIItemEditSendKeys1, true);

            // Type '********' in text box
            Keyboard.SendKeys(uIItemEdit3, this.ChangeUserCredentialsParams.UIItemEditSendKeys2, true);

            // Type '1' in text box
            uIItemEdit4.Text = this.ChangeUserCredentialsParams.UIItemEditText2;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit4, this.ChangeUserCredentialsParams.UIItemEditSendKeys3, ModifierKeys.None);

            // Type '********' in text box
            Keyboard.SendKeys(uIItemEdit5, this.ChangeUserCredentialsParams.UIItemEditSendKeys4, true);

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit6, this.ChangeUserCredentialsParams.UIItemEditSendKeys5, ModifierKeys.None);

            // Type '5010' in text box
            uIItemEdit7.Text = this.ChangeUserCredentialsParams.UIItemEditText3;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit8, this.ChangeUserCredentialsParams.UIItemEditSendKeys6, ModifierKeys.None);

            // Type '5020' in text box
            uIItemEdit9.Text = this.ChangeUserCredentialsParams.UIItemEditText4;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit10, this.ChangeUserCredentialsParams.UIItemEditSendKeys7, ModifierKeys.None);

            // Type '5030' in text box
            uIItemEdit11.Text = this.ChangeUserCredentialsParams.UIItemEditText5;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit12, this.ChangeUserCredentialsParams.UIItemEditSendKeys8, ModifierKeys.None);

            // Type '5010' in text box
            uIItemEdit13.Text = this.ChangeUserCredentialsParams.UIItemEditText6;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit13, this.ChangeUserCredentialsParams.UIItemEditSendKeys9, ModifierKeys.None);

            // Type '20.03.2020' in text box
            uIItemEdit14.Text = this.ChangeUserCredentialsParams.UIItemEditText7;

            // Type '{Tab}' in text box
            Keyboard.SendKeys(uIItemEdit14, this.ChangeUserCredentialsParams.UIItemEditSendKeys10, ModifierKeys.None);

            // Type '20.03.2099' in text box
            uIItemEdit15.Text = this.ChangeUserCredentialsParams.UIItemEditText8;

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(20, 21));
        }
        
        /// <summary>
        /// OpenTable1
        /// </summary>
        public void OpenTable1()
        {
            #region Variable Declarations
            WinClient uIGenerellloggingClient = this.UILoggWindow.UIItemWindow.UIGenerellloggingClient;
            #endregion

            // Click 'Generell logging' client
            Mouse.Click(uIGenerellloggingClient, new Point(218, 27));

            // Right-Click 'Generell logging' client
            Mouse.Click(uIGenerellloggingClient, MouseButtons.Right, ModifierKeys.None, new Point(218, 27));
        }
        
        /// <summary>
        /// OpenTable2
        /// </summary>
        public void OpenTable2()
        {
            #region Variable Declarations
            WinClient uIGenerellloggingClient = this.UILoggWindow.UIItemWindow1.UIGenerellloggingClient;
            #endregion

            // Right-Click 'Generell logging' client
            Mouse.Click(uIGenerellloggingClient, MouseButtons.Right, ModifierKeys.None, new Point(97, 26));
        }
        
        /// <summary>
        /// SortTable1
        /// </summary>
        public void SortTable1()
        {
            #region Variable Declarations
            WinClient uIGenerellloggingClient = this.UILoggWindow.UIItemWindow.UIGenerellloggingClient;
            #endregion

            // Click 'Generell logging' client
            Mouse.Click(uIGenerellloggingClient, new Point(250, 9));
        }
        
        /// <summary>
        /// SortTable2
        /// </summary>
        public void SortTable2()
        {
            #region Variable Declarations
            WinClient uIGenerellloggingClient = this.UILoggWindow.UIItemWindow1.UIGenerellloggingClient;
            #endregion

            // Click 'Generell logging' client
            Mouse.Click(uIGenerellloggingClient, new Point(43, 6));
        }
        
        #region Properties
        public virtual ChangeUserCredentialsParams ChangeUserCredentialsParams
        {
            get
            {
                if ((this.mChangeUserCredentialsParams == null))
                {
                    this.mChangeUserCredentialsParams = new ChangeUserCredentialsParams();
                }
                return this.mChangeUserCredentialsParams;
            }
        }
        
        public UILoggWindow UILoggWindow
        {
            get
            {
                if ((this.mUILoggWindow == null))
                {
                    this.mUILoggWindow = new UILoggWindow();
                }
                return this.mUILoggWindow;
            }
        }
        
        public UIBrukeradministrasjonWindow UIBrukeradministrasjonWindow
        {
            get
            {
                if ((this.mUIBrukeradministrasjonWindow == null))
                {
                    this.mUIBrukeradministrasjonWindow = new UIBrukeradministrasjonWindow();
                }
                return this.mUIBrukeradministrasjonWindow;
            }
        }
        
        public UINivåWindow UINivåWindow
        {
            get
            {
                if ((this.mUINivåWindow == null))
                {
                    this.mUINivåWindow = new UINivåWindow();
                }
                return this.mUINivåWindow;
            }
        }
        #endregion
        
        #region Fields
        private ChangeUserCredentialsParams mChangeUserCredentialsParams;
        
        private UILoggWindow mUILoggWindow;
        
        private UIBrukeradministrasjonWindow mUIBrukeradministrasjonWindow;
        
        private UINivåWindow mUINivåWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ChangeUserCredentials'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class ChangeUserCredentialsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'BASTANT2' in text box
        /// </summary>
        public string UIItemEditText = "BASTANT2";
        
        /// <summary>
        /// Type 'BJARNE2' in text box
        /// </summary>
        public string UIItemEditText1 = "BJARNE2";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "e3fAP5nj0xU/fLLlsMnLN8doTlYKY9Jg";
        
        /// <summary>
        /// Type '********' in text box
        /// </summary>
        public string UIItemEditSendKeys2 = "e3fAP5nj0xU/fLLlsMnLN8doTlYKY9Jg";
        
        /// <summary>
        /// Type '1' in text box
        /// </summary>
        public string UIItemEditText2 = "1";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys3 = "{Tab}";
        
        /// <summary>
        /// Type '********' in text box
        /// </summary>
        public string UIItemEditSendKeys4 = "jU4c6NneSjOdTsK52vyU9sYtZJwyictu";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys5 = "{Tab}";
        
        /// <summary>
        /// Type '5010' in text box
        /// </summary>
        public string UIItemEditText3 = "5010";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys6 = "{Tab}";
        
        /// <summary>
        /// Type '5020' in text box
        /// </summary>
        public string UIItemEditText4 = "5020";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys7 = "{Tab}";
        
        /// <summary>
        /// Type '5030' in text box
        /// </summary>
        public string UIItemEditText5 = "5030";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys8 = "{Tab}";
        
        /// <summary>
        /// Type '5010' in text box
        /// </summary>
        public string UIItemEditText6 = "5010";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys9 = "{Tab}";
        
        /// <summary>
        /// Type '20.03.2020' in text box
        /// </summary>
        public string UIItemEditText7 = "20.03.2020";
        
        /// <summary>
        /// Type '{Tab}' in text box
        /// </summary>
        public string UIItemEditSendKeys10 = "{Tab}";
        
        /// <summary>
        /// Type '20.03.2099' in text box
        /// </summary>
        public string UIItemEditText8 = "20.03.2099";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILoggWindow : WinWindow
    {
        
        public UILoggWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Logg";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TfmLogSeekView";
            this.WindowTitles.Add("Logg");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxGridSite";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Logg");
            #endregion
        }
        
        #region Properties
        public WinClient UIGenerellloggingClient
        {
            get
            {
                if ((this.mUIGenerellloggingClient == null))
                {
                    this.mUIGenerellloggingClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIGenerellloggingClient.WindowTitles.Add("Logg");
                    #endregion
                }
                return this.mUIGenerellloggingClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIGenerellloggingClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxGridSite";
            this.WindowTitles.Add("Logg");
            #endregion
        }
        
        #region Properties
        public WinClient UIGenerellloggingClient
        {
            get
            {
                if ((this.mUIGenerellloggingClient == null))
                {
                    this.mUIGenerellloggingClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIGenerellloggingClient.WindowTitles.Add("Logg");
                    #endregion
                }
                return this.mUIGenerellloggingClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIGenerellloggingClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrukeradministrasjonWindow : WinWindow
    {
        
        public UIBrukeradministrasjonWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Bruker administrasjon";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TfrmFullAdm";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow21 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow21(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItem0x49ffc19754541dWindow UIItem0x49ffc19754541dWindow
        {
            get
            {
                if ((this.mUIItem0x49ffc19754541dWindow == null))
                {
                    this.mUIItem0x49ffc19754541dWindow = new UIItem0x49ffc19754541dWindow(this);
                }
                return this.mUIItem0x49ffc19754541dWindow;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        
        public UIItemWindow211 UIItemWindow21
        {
            get
            {
                if ((this.mUIItemWindow21 == null))
                {
                    this.mUIItemWindow21 = new UIItemWindow211(this);
                }
                return this.mUIItemWindow21;
            }
        }
        
        public UIItemWindow31 UIItemWindow31
        {
            get
            {
                if ((this.mUIItemWindow31 == null))
                {
                    this.mUIItemWindow31 = new UIItemWindow31(this);
                }
                return this.mUIItemWindow31;
            }
        }
        
        public UIItem0xf427ef86dcac25Window UIItem0xf427ef86dcac25Window
        {
            get
            {
                if ((this.mUIItem0xf427ef86dcac25Window == null))
                {
                    this.mUIItem0xf427ef86dcac25Window = new UIItem0xf427ef86dcac25Window(this);
                }
                return this.mUIItem0xf427ef86dcac25Window;
            }
        }
        
        public UIItemWindow5 UIItemWindow5
        {
            get
            {
                if ((this.mUIItemWindow5 == null))
                {
                    this.mUIItemWindow5 = new UIItemWindow5(this);
                }
                return this.mUIItemWindow5;
            }
        }
        
        public UIItemWindow6 UIItemWindow6
        {
            get
            {
                if ((this.mUIItemWindow6 == null))
                {
                    this.mUIItemWindow6 = new UIItemWindow6(this);
                }
                return this.mUIItemWindow6;
            }
        }
        
        public UIItemWindow7 UIItemWindow7
        {
            get
            {
                if ((this.mUIItemWindow7 == null))
                {
                    this.mUIItemWindow7 = new UIItemWindow7(this);
                }
                return this.mUIItemWindow7;
            }
        }
        
        public UIItemWindow8 UIItemWindow8
        {
            get
            {
                if ((this.mUIItemWindow8 == null))
                {
                    this.mUIItemWindow8 = new UIItemWindow8(this);
                }
                return this.mUIItemWindow8;
            }
        }
        
        public UIItemWindow9 UIItemWindow9
        {
            get
            {
                if ((this.mUIItemWindow9 == null))
                {
                    this.mUIItemWindow9 = new UIItemWindow9(this);
                }
                return this.mUIItemWindow9;
            }
        }
        
        public UIItemWindow10 UIItemWindow10
        {
            get
            {
                if ((this.mUIItemWindow10 == null))
                {
                    this.mUIItemWindow10 = new UIItemWindow10(this);
                }
                return this.mUIItemWindow10;
            }
        }
        
        public UIItemWindow81 UIItemWindow81
        {
            get
            {
                if ((this.mUIItemWindow81 == null))
                {
                    this.mUIItemWindow81 = new UIItemWindow81(this);
                }
                return this.mUIItemWindow81;
            }
        }
        
        public UIItemWindow82 UIItemWindow82
        {
            get
            {
                if ((this.mUIItemWindow82 == null))
                {
                    this.mUIItemWindow82 = new UIItemWindow82(this);
                }
                return this.mUIItemWindow82;
            }
        }
        
        public UIItemWindow91 UIItemWindow91
        {
            get
            {
                if ((this.mUIItemWindow91 == null))
                {
                    this.mUIItemWindow91 = new UIItemWindow91(this);
                }
                return this.mUIItemWindow91;
            }
        }
        
        public UIItemWindow92 UIItemWindow92
        {
            get
            {
                if ((this.mUIItemWindow92 == null))
                {
                    this.mUIItemWindow92 = new UIItemWindow92(this);
                }
                return this.mUIItemWindow92;
            }
        }
        
        public UIItemWindow101 UIItemWindow101
        {
            get
            {
                if ((this.mUIItemWindow101 == null))
                {
                    this.mUIItemWindow101 = new UIItemWindow101(this);
                }
                return this.mUIItemWindow101;
            }
        }
        
        public UIItemWindow102 UIItemWindow102
        {
            get
            {
                if ((this.mUIItemWindow102 == null))
                {
                    this.mUIItemWindow102 = new UIItemWindow102(this);
                }
                return this.mUIItemWindow102;
            }
        }
        
        public UIItemWindow13 UIItemWindow13
        {
            get
            {
                if ((this.mUIItemWindow13 == null))
                {
                    this.mUIItemWindow13 = new UIItemWindow13(this);
                }
                return this.mUIItemWindow13;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow21 mUIItemWindow2;
        
        private UIItem0x49ffc19754541dWindow mUIItem0x49ffc19754541dWindow;
        
        private UIItemWindow3 mUIItemWindow3;
        
        private UIItemWindow211 mUIItemWindow21;
        
        private UIItemWindow31 mUIItemWindow31;
        
        private UIItem0xf427ef86dcac25Window mUIItem0xf427ef86dcac25Window;
        
        private UIItemWindow5 mUIItemWindow5;
        
        private UIItemWindow6 mUIItemWindow6;
        
        private UIItemWindow7 mUIItemWindow7;
        
        private UIItemWindow8 mUIItemWindow8;
        
        private UIItemWindow9 mUIItemWindow9;
        
        private UIItemWindow10 mUIItemWindow10;
        
        private UIItemWindow81 mUIItemWindow81;
        
        private UIItemWindow82 mUIItemWindow82;
        
        private UIItemWindow91 mUIItemWindow91;
        
        private UIItemWindow92 mUIItemWindow92;
        
        private UIItemWindow101 mUIItemWindow101;
        
        private UIItemWindow102 mUIItemWindow102;
        
        private UIItemWindow13 mUIItemWindow13;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxGridSite";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinClient UIPanel16Client
        {
            get
            {
                if ((this.mUIPanel16Client == null))
                {
                    this.mUIPanel16Client = new WinClient(this);
                    #region Search Criteria
                    this.mUIPanel16Client.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIPanel16Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIPanel16Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TicMenuButton";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIItemClient.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow21 : WinWindow
    {
        
        public UIItemWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "11";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItem0x49ffc19754541dWindow : WinWindow
    {
        
        public UIItem0x49ffc19754541dWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "0x49ffc19754541d42dba573b39112d5e7eb81b880";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = " ";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "8";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = " ";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow211 : WinWindow
    {
        
        public UIItemWindow211(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "12";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow31 : WinWindow
    {
        
        public UIItemWindow31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "10";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItem0xf427ef86dcac25Window : WinWindow
    {
        
        public UIItem0xf427ef86dcac25Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "0xf427ef86dcac2524978ac300847f6fc2c79e10f5";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow5 : WinWindow
    {
        
        public UIItemWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow6 : WinWindow
    {
        
        public UIItemWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow7 : WinWindow
    {
        
        public UIItemWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "8";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow8 : WinWindow
    {
        
        public UIItemWindow8(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = " ";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public UIItemClient1 UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient1(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient1 mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemClient1 : WinClient
    {
        
        public UIItemClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = " ";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.Name] = "...";
                    this.mUIItemButton.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WinButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WinButton.PropertyNames.Name] = "...";
                    this.mUIItemButton1.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WinButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WinButton.PropertyNames.Name] = "...";
                    this.mUIItemButton2.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WinButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WinButton.PropertyNames.Name] = "...";
                    this.mUIItemButton3.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        
        private WinButton mUIItemButton1;
        
        private WinButton mUIItemButton2;
        
        private WinButton mUIItemButton3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow9 : WinWindow
    {
        
        public UIItemWindow9(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TicDateEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow10 : WinWindow
    {
        
        public UIItemWindow10(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TicDateEdit";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow81 : WinWindow
    {
        
        public UIItemWindow81(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow82 : WinWindow
    {
        
        public UIItemWindow82(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow91 : WinWindow
    {
        
        public UIItemWindow91(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow92 : WinWindow
    {
        
        public UIItemWindow92(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow101 : WinWindow
    {
        
        public UIItemWindow101(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow102 : WinWindow
    {
        
        public UIItemWindow102(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow13 : WinWindow
    {
        
        public UIItemWindow13(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMSEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.WindowTitles.Add("Bruker administrasjon");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Bruker administrasjon");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINivåWindow : DXWindow
    {
        
        public UINivåWindow()
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "Nivå";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public UIGsLayoutControl1Custom UIGsLayoutControl1Custom
        {
            get
            {
                if ((this.mUIGsLayoutControl1Custom == null))
                {
                    this.mUIGsLayoutControl1Custom = new UIGsLayoutControl1Custom(this);
                }
                return this.mUIGsLayoutControl1Custom;
            }
        }
        
        public UIGsPanelControl2Client UIGsPanelControl2Client
        {
            get
            {
                if ((this.mUIGsPanelControl2Client == null))
                {
                    this.mUIGsPanelControl2Client = new UIGsPanelControl2Client(this);
                }
                return this.mUIGsPanelControl2Client;
            }
        }
        #endregion
        
        #region Fields
        private UIGsLayoutControl1Custom mUIGsLayoutControl1Custom;
        
        private UIGsPanelControl2Client mUIGsPanelControl2Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGsLayoutControl1Custom : DXTestControl
    {
        
        public UIGsLayoutControl1Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "gsLayoutControl1";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GSLayoutControl";
            this.SearchProperties[DXTestControl.PropertyNames.HierarchyLevel] = "2";
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public UILayoutControlGroup1LayoutGroup UILayoutControlGroup1LayoutGroup
        {
            get
            {
                if ((this.mUILayoutControlGroup1LayoutGroup == null))
                {
                    this.mUILayoutControlGroup1LayoutGroup = new UILayoutControlGroup1LayoutGroup(this);
                }
                return this.mUILayoutControlGroup1LayoutGroup;
            }
        }
        #endregion
        
        #region Fields
        private UILayoutControlGroup1LayoutGroup mUILayoutControlGroup1LayoutGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILayoutControlGroup1LayoutGroup : DXBaseLayoutItem
    {
        
        public UILayoutControlGroup1LayoutGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "layoutControlGroup1";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutGroup";
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public UILayDepartmentsLayoutControlItem UILayDepartmentsLayoutControlItem
        {
            get
            {
                if ((this.mUILayDepartmentsLayoutControlItem == null))
                {
                    this.mUILayDepartmentsLayoutControlItem = new UILayDepartmentsLayoutControlItem(this);
                }
                return this.mUILayDepartmentsLayoutControlItem;
            }
        }
        #endregion
        
        #region Fields
        private UILayDepartmentsLayoutControlItem mUILayDepartmentsLayoutControlItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILayDepartmentsLayoutControlItem : DXBaseLayoutItem
    {
        
        public UILayDepartmentsLayoutControlItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "LayDepartments";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LayoutControlItem";
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public UIGbDepartmentsClient UIGbDepartmentsClient
        {
            get
            {
                if ((this.mUIGbDepartmentsClient == null))
                {
                    this.mUIGbDepartmentsClient = new UIGbDepartmentsClient(this);
                }
                return this.mUIGbDepartmentsClient;
            }
        }
        #endregion
        
        #region Fields
        private UIGbDepartmentsClient mUIGbDepartmentsClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGbDepartmentsClient : DXTestControl
    {
        
        public UIGbDepartmentsClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "gbDepartments";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GSGroupControl";
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public UIGDepartmentsTable UIGDepartmentsTable
        {
            get
            {
                if ((this.mUIGDepartmentsTable == null))
                {
                    this.mUIGDepartmentsTable = new UIGDepartmentsTable(this);
                }
                return this.mUIGDepartmentsTable;
            }
        }
        #endregion
        
        #region Fields
        private UIGDepartmentsTable mUIGDepartmentsTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGDepartmentsTable : DXGrid
    {
        
        public UIGDepartmentsTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "gDepartments";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GSGridControl";
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public DXCell UIItem5010ArbeidsplanoCell
        {
            get
            {
                if ((this.mUIItem5010ArbeidsplanoCell == null))
                {
                    this.mUIItem5010ArbeidsplanoCell = new DXCell(this);
                    #region Search Criteria
                    this.mUIItem5010ArbeidsplanoCell.SearchProperties[DXTestControl.PropertyNames.Name] = "gDepartmentsGridControlCell[View]gvDepartments[Row]46[Column]cDepName";
                    this.mUIItem5010ArbeidsplanoCell.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GridControlCell";
                    this.mUIItem5010ArbeidsplanoCell.WindowTitles.Add("Nivå");
                    #endregion
                }
                return this.mUIItem5010ArbeidsplanoCell;
            }
        }
        
        public DXCell UIItem5020KalenderplanCell
        {
            get
            {
                if ((this.mUIItem5020KalenderplanCell == null))
                {
                    this.mUIItem5020KalenderplanCell = new DXCell(this);
                    #region Search Criteria
                    this.mUIItem5020KalenderplanCell.SearchProperties[DXTestControl.PropertyNames.Name] = "gDepartmentsGridControlCell[View]gvDepartments[Row]47[Column]cDepName";
                    this.mUIItem5020KalenderplanCell.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GridControlCell";
                    this.mUIItem5020KalenderplanCell.WindowTitles.Add("Nivå");
                    #endregion
                }
                return this.mUIItem5020KalenderplanCell;
            }
        }
        
        public DXCell UIItem5030ØnskeplanCell
        {
            get
            {
                if ((this.mUIItem5030ØnskeplanCell == null))
                {
                    this.mUIItem5030ØnskeplanCell = new DXCell(this);
                    #region Search Criteria
                    this.mUIItem5030ØnskeplanCell.SearchProperties[DXTestControl.PropertyNames.Name] = "gDepartmentsGridControlCell[View]gvDepartments[Row]48[Column]cDepName";
                    this.mUIItem5030ØnskeplanCell.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GridControlCell";
                    this.mUIItem5030ØnskeplanCell.WindowTitles.Add("Nivå");
                    #endregion
                }
                return this.mUIItem5030ØnskeplanCell;
            }
        }
        #endregion
        
        #region Fields
        private DXCell mUIItem5010ArbeidsplanoCell;
        
        private DXCell mUIItem5020KalenderplanCell;
        
        private DXCell mUIItem5030ØnskeplanCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGsPanelControl2Client : DXTestControl
    {
        
        public UIGsPanelControl2Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "gsPanelControl2";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GSPanelControl";
            this.WindowTitles.Add("Nivå");
            #endregion
        }
        
        #region Properties
        public DXButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnOK";
                    this.mUIOKButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "GSSimpleButton";
                    this.mUIOKButton.WindowTitles.Add("Nivå");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUIOKButton;
        #endregion
    }
}
